RESOURCES_FOLDER = "./resources/"
DATASET = RESOURCES_FOLDER + "dataset/milei"

INPUT_VIDEO = "video_to_analyze.mp4"
INPUT_VIDEO_PATH = RESOURCES_FOLDER + INPUT_VIDEO

OUTPUT_VIDEO = "tmp_video_with_analysis.mp4"
OUTPUT_PROCESSED_VIDEO_PATH = RESOURCES_FOLDER + OUTPUT_VIDEO
OUTPUT_VIDEO_PATH = RESOURCES_FOLDER + OUTPUT_VIDEO
OUTPUT_VIDEO_WITH_AUDIO = "video_analyzed.mp4"
OUTPUT_VIDEO_WITH_AUDIO_PATH = RESOURCES_FOLDER + OUTPUT_VIDEO_WITH_AUDIO

TMP_AUDIO = "tmp_audio_" + INPUT_VIDEO
TMP_AUDIO_PATH = RESOURCES_FOLDER + TMP_AUDIO

TMP_AUDIO_CLIPPED = "tmp_audio_clipped_" + INPUT_VIDEO
TMP_AUDIO_CLIPPED_PATH = RESOURCES_FOLDER + TMP_AUDIO_CLIPPED

FACE_TO_ANALYZE = "tmp_face_to_analyze.png"
FACE_TO_ANALYZE_PATH = RESOURCES_FOLDER + FACE_TO_ANALYZE
